---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-single
  namespace: elk
spec:
  selector:
    matchLabels:
      app: kb-single
  replicas: 1
  template:
    metadata:
      name: kb-single
      labels:
        app: kb-single
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:6.4.0
        name: kb
        env:
        - name: ELASTICSEARCH_URL
          value: "http://es-single:9200"
        ports:
        - name: http
          containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kb-single-svc
  namespace: elk
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5601
    targetPort: 5601 
  selector:
    app: kb-single            

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-single
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-single
  template:
    metadata:
      name: es-single
      labels:
        app: es-single
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        name: es
        env:
        - name: network.host
          value: "_site_"
        - name: node.name
          value: "${HOSTNAME}"
        - name: discovery.zen.ping.unicast.hosts
          value: "${ES_SINGLE_NODEPORT_SERVICE_HOST}"
        - name: cluster.name
          value: "uk8s-single"
        - name: ES_JAVA_OPTS
          value: "-Xms128m -Xmx128m"
        volumeMounts:
        - name: es-single-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-single-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata: 
  name: es-single-nodeport
  namespace: elk
spec:
  type: NodePort
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 31200
  - name: tcp
    port: 9300
    targetPort: 9300
    nodePort: 31300
  selector:
    app: es-single

---
apiVersion: v1
kind: Service
metadata:
  name: es-single
  namespace: elk
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9200
  - name: tcp
    port: 9300
  selector:
    app: es-single
